### ISSUE TITLE
Long monster names cannot be queried

### ISSUE THREAD

**Issue by AmyBSOD** [UnNetHack/pinobot#1]
Seen with the SLEX monster "bust supersecret advice rifling unverified bosoming"; the line that checks "T.length text >= 50" would probably need to be changed to a higher value, I'd suggest setting it to 100 due to SLEX monster names sometimes being pretty long ;)

**Comment by Noeda** [comment]
I just tried this on #hardfought:

```
<Adeon> @le?bust supersecret advice rifling unverified bosoming
14:00:15 <+Beholder> bust supersecret advice rifling unverified bosoming (u) | Lvl: 7 | Diff: 12 | Spd: 19 | Res: disintegrate drain | Confers: nothing | MR: 62 | Generates: special | AC: 1 | Attacks: 7d7 gaze curse-armor, 6d8 bite clerical | Alignment: -7 | Flags: amorphous, phases, conceals, demon, passes-bars
```

And I seem to get results. The length is 60 now. So I think we are good with this for now.
