### ISSUE TITLE
xnethack and splicehack aren't in there

### ISSUE THREAD

**Issue by RojjaCebolla** [UnNetHack/pinobot#4]
if you want 'em, they're at
https://github.com/copperwater/xNetHack
https://github.com/NullCGT/SpliceHack

**Comment by k21971** [comment]
The monster list between vanilla NetHack 3.7 and xNetHack are virtually identical, but there are some differences with some of the monster templates. A couple of the monster symbols are different also. Probably worth doing.

**Comment by Noeda** [comment]
Now they are 🌮
